# Generated by Django 5.0.1 on 2024-01-28 12:58

import inspectors.data_validate_inspector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        editable=False,
                        max_length=200,
                        validators=[inspectors.data_validate_inspector.check_str],
                    ),
                ),
                ("product_was_used_counter", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "recipe_name",
                    models.CharField(
                        editable=False,
                        max_length=200,
                        validators=[inspectors.data_validate_inspector.check_str],
                    ),
                ),
                ("product_list", models.JSONField(default=dict)),
            ],
        ),
    ]
